name: "{{package}}"

on:
  push:
    paths:
      - "src/{{package}}/**"
      - ".github/workflows/{{package}}.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Run tests
        run: |-
          cd src/{{package}}
          go test ./...