name: "bikestore"

on:
  push:
    paths:
      - "src/bikestore/**"
      - ".github/workflows/bikestore.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
          cache: false

      - name: Run tests
        run: |-
          cd src/bikestore
          go test ./... -json > TestResults-bikestore.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-bikestore
          path: src/bikestore/TestResults-bikestore.json
