name: "bookstore"

on:
  push:
    paths:
      - "src/bookstore/**"
      - ".github/workflows/bookstore.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          
      - name: Run tests
        run: |-
          cd src/bookstore
          go test ./...
