name: "calculator"

on:
  push:
    paths:
      - "src/calculator/**"
      - ".github/workflows/calculator.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
          cache: false
          
      - name: Run tests
        run: |-
          cd src/calculator
          go test ./...
