name: "creditcard"

on:
  push:
    paths:
      - "src/creditcard/**"
      - ".github/workflows/creditcard.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
          cache: false

      - name: Run tests
        run: |-
          cd src/creditcard
          go test ./... -json > TestResults-creditcard.json

      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-creditcard
          path: src/creditcard/TestResults-creditcard.json
